# frozen_string_literal: true

require "net/http"
require "json"
require "uri"

module Hmrc
  class Oauth
    TOKEN_PATH = "/oauth/token".freeze

    # Build the HMRC authorization URL. `state` is a CSRF token generated by
    # the controller and stored in session — verified on callback.
    def self.authorization_url(redirect_uri:, state:)
      params = URI.encode_www_form(
        response_type: "code",
        client_id:     Config.client_id,
        scope:         Config::SCOPES,
        redirect_uri:  redirect_uri,
        state:         state
      )
      "#{Config::OAUTH_BASE}/oauth/authorize?#{params}"
    end

    # Exchange an authorization code for access + refresh tokens. Returns
    # :access_token, :refresh_token, :expires_in.
    #
    # The form fields go in an explicit HASH. post_token takes one positional
    # argument plus a `base:` keyword, so bare keyword syntax here would be read
    # as keywords and the positional would never arrive. That raises only on a
    # real token exchange, which no test does.
    def self.exchange_code(code:, redirect_uri:)
      post_token(
        {
          grant_type:    "authorization_code",
          code:          code,
          redirect_uri:  redirect_uri,
          client_id:     Config.client_id,
          client_secret: Config.client_secret
        }
      )
    end

    # Use a refresh token to get a new access token. Returns :access_token,
    # :expires_in, and possibly a new :refresh_token. Explicit hash, same reason
    # as above.
    def self.refresh(refresh_token:)
      post_token(
        {
          grant_type:    "refresh_token",
          refresh_token: refresh_token,
          client_id:     Config.client_id,
          client_secret: Config.client_secret
        }
      )
    end

    # Application-restricted access token (client-credentials grant), for
    # endpoints with no user context — the Test Fraud Prevention Headers
    # validator. `sandbox: true` forces the sandbox environment regardless of
    # the global production flag, because the FPH validator only exists there.
    def self.application_token(sandbox: false)
      client_id     = sandbox ? Config.sandbox_client_id     : Config.client_id
      client_secret = sandbox ? Config.sandbox_client_secret : Config.client_secret
      base          = sandbox ? Config::SANDBOX_API_BASE      : Config::API_BASE

      post_token(
        { grant_type: "client_credentials", client_id: client_id, client_secret: client_secret },
        base: base
      )[:access_token]
    end

    # Ensure a taxpayer's permission is fresh before making an API call:
    # refreshes if the access token expires within 5 minutes, and saves. Raises
    # if no refresh token is present.
    def self.ensure_fresh!(taxpayer)
      return unless taxpayer&.token_expires_at
      return if taxpayer.token_expires_at > 5.minutes.from_now

      result = refresh(refresh_token: taxpayer.refresh_token)
      taxpayer.update!(
        access_token:     result[:access_token],
        # HMRC does not always issue a new refresh token; keep the old one
        # rather than blanking it, or the next refresh has nothing to send.
        refresh_token:    result[:refresh_token] || taxpayer.refresh_token,
        token_expires_at: Time.current + result[:expires_in].to_i.seconds
      )
    end

    private_class_method def self.post_token(params, base: Config::API_BASE)
      uri  = URI("#{base}#{TOKEN_PATH}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl      = true
      http.open_timeout = 10
      http.read_timeout = 20

      request = Net::HTTP::Post.new(uri.path)
      request.set_form_data(params)
      request["Accept"] = "application/vnd.hmrc.1.0+json"

      response = http.request(request)
      body = JSON.parse(response.body)

      unless response.is_a?(Net::HTTPSuccess)
        raise "HMRC OAuth error #{response.code}: #{body['error_description'] || body['error']}"
      end

      {
        access_token:  body["access_token"],
        refresh_token: body["refresh_token"],
        expires_in:    body["expires_in"].to_i
      }
    end
  end
end
